In [35]:
import numpy as np 
import pandas as pd 
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [36]:
df = pd.read_csv('car_price_dataset.csv')
df.head()

        Brand   Model  Year  Engine_Size  ... Mileage Doors  Owner_Count  Price
0         Kia     Rio  2020          4.2  ...  289944     3            5   8501
1   Chevrolet  Malibu  2012          2.0  ...    5356     2            3  12092
2    Mercedes     GLA  2020          4.2  ...  231440     4            2  11171
3        Audi      Q5  2023          2.0  ...  160971     2            1  11780
4  Volkswagen    Golf  2003          2.6  ...  286618     3            3   2867

[5 rows x 10 columns]

* Mainly it pandas is not used for machine learning in case to generate dummie variables, techniqualy sk.learn library is used

### 1. One Hot Encoding using Pandas

In [37]:
pd.get_dummies(df, columns=["Fuel_Type", "Owner_Count"], dtype=int)

           Brand     Model  Year  ...  Owner_Count_3 Owner_Count_4  Owner_Count_5
0            Kia       Rio  2020  ...              0             0              1
1      Chevrolet    Malibu  2012  ...              1             0              0
2       Mercedes       GLA  2020  ...              0             0              0
3           Audi        Q5  2023  ...              0             0              0
4     Volkswagen      Golf  2003  ...              1             0              0
...          ...       ...   ...  ...            ...           ...            ...
9995         Kia    Optima  2004  ...              0             1              0
9996   Chevrolet    Impala  2002  ...              0             0              0
9997         BMW  3 Series  2010  ...              0             0              0
9998        Ford  Explorer  2002  ...              0             0              0
9999  Volkswagen    Tiguan  2001  ...              1             0              0

[10000 rows x 17 columns]

### 2. K-1 One Hot Encoding

In [38]:
pd.get_dummies(df, columns=["Fuel_Type", "Owner_Count"], drop_first=True, dtype=int)

           Brand     Model  Year  ...  Owner_Count_3 Owner_Count_4  Owner_Count_5
0            Kia       Rio  2020  ...              0             0              1
1      Chevrolet    Malibu  2012  ...              1             0              0
2       Mercedes       GLA  2020  ...              0             0              0
3           Audi        Q5  2023  ...              0             0              0
4     Volkswagen      Golf  2003  ...              1             0              0
...          ...       ...   ...  ...            ...           ...            ...
9995         Kia    Optima  2004  ...              0             1              0
9996   Chevrolet    Impala  2002  ...              0             0              0
9997         BMW  3 Series  2010  ...              0             0              0
9998        Ford  Explorer  2002  ...              0             0              0
9999  Volkswagen    Tiguan  2001  ...              1             0              0

[10000 rows x 15 columns]

## 3. One Hot Encoding using Sklearn

#### after spliting data into Xtrain, Xtest, ytrain, ytest ie in model

In [39]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:9], df.Price, test_size=0.2, random_state=11)
X_train.head()

           Brand     Model  Year  ...  Mileage Doors Owner_Count
4199        Ford  Explorer  2004  ...   290006     2           5
757          Kia  Sportage  2005  ...     2587     4           5
4001    Mercedes   C-Class  2008  ...   126886     4           3
8163        Ford  Explorer  2014  ...   136281     3           1
4250  Volkswagen    Tiguan  2012  ...    16715     2           2

[5 rows x 9 columns]

In [60]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', dtype=int)                  # to remove the 1st column

In [41]:
# ohe.fit_transform(X_train[['Fuel_Type', 'Owner_Count']])

In [61]:
X_train_new = ohe.fit_transform(X_train[['Fuel_Type', 'Owner_Count']]).toarray()
X_train_new

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], shape=(8000, 7))

In [62]:
X_test_new = ohe.fit_transform(X_train[['Fuel_Type', 'Owner_Count']]).toarray()
X_test_new

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], shape=(8000, 7))

In [52]:
X_train_new.shape

(8000, 7)

#### withous removing first columns of each nominal columns, why? for reducing multi co-linearity

In [58]:
X_train_new.shape

(8000, 9)